# Generated by Django 6.0.5 on 2026-06-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
