# Generated by Django 6.0.5 on 2026-06-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0003_alter_order_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
