# Generated by Django 6.0.5 on 2026-06-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0005_foodtracking_orderaddress_paymentdetail_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
