# Generated by Django 6.0.5 on 2026-06-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0006_alter_paymentdetail_payment_date_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
