# Generated by Django 6.0.6 on 2026-08-21 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foodordering", "0007_alter_paymentdetail_payment_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentdetail",
            name="card_number",
        ),
        migrations.RemoveField(
            model_name="paymentdetail",
            name="cvv",
        ),
        migrations.RemoveField(
            model_name="paymentdetail",
            name="expiry_date",
        ),
    ]
